#!/bin/sh

# Run tests
cd backend
npm run test

# Capture the exit code of npm test
if [ $? -ne 0 ]; then
  echo "Tests failed. Commit is being aborted and changes are being unstaged. Please fix the failing tests and try again."

  # Unstage changes if tests fail
  git reset

  exit 1
fi

cd ..
